### ISSUE TITLE
/get_by_search?type=song results in error

### ISSUE THREAD

**Issue by onespaceman** [diraimondo/gmusicproxy#37]
Trying to add songs from search results in
> error adding Binary file (standard input) matches: Not found

Debug Log:

[INFO] (mobileclient:68): authenticated
[DEBUG] (GMusicProxy:558): Fetching lastest version of gmusicproxy...
[DEBUG] (GMusicProxy:560): latest available version: 1.0.1
[DEBUG] (GMusicProxy:561): installed version: 1.0.1
[INFO] (GMusicProxy:641): Listening on port 9999...
[DEBUG] (GMusicProxy:34): request path: /get_by_search?type=song&artist=Geographer&title=Kaleidoscope
[INFO] (GMusicProxy:353): Searching for song with query: Geographer Kaleidoscope
[DEBUG] (shared:202): Search(args=[u'Geographer Kaleidoscope', 50], kwargs={})
[DEBUG] (shared:243): {u'kind': u'sj#searchresponse', u'clusterOrder': [u'5', u'2', u'3', u'1', u'7', u'6', u'4', u'8'], u'entries': [{u'navigational_result': False, u'score': 165.54998779296875, u'type': u'2', u'best_result': False, u'artist': {u'kind': u'sj#artist', u'artistArtRef': u'http://lh3.googleusercontent.com/ZIgRRfW34Kv2vJ5O1-5GqsmSVSkJBMn9g60hnvc-0UaHLAUWBXbg__pfHE2MG7Wp60fKW-F0bsw', u'name': u'Geographer', u'artistId': u'A4aopp74j4zwlxd4pbvtfnncf3i', u'artist_bio_attribution': {u'kind': u'sj#attribution', u'source_title': u'artist representative'}}}, {u'track': {u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}], u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'], u'composer': u'', u'year': 2012, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Myth', u'title': u'Kaleidoscope', u'albumArtist': u'Geographer', u'trackNumber': 3, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'Txwp6zm4g6qrc3zkhihpz67ryza', u'nid': u'Txwp6zm4g6qrc3zkhihpz67ryza', u'estimatedSize': u'11104163', u'albumId': u'Bfvh2badashiwhiwapiolvhd34m', u'genre': u'Alternative/Indie', u'kind': u'sj#track', u'artist': u'Geographer', u'durationMillis': u'277000'}, u'navigational_result': False, u'score': 150.19752502441406, u'type': u'1', u'best_result': False}, {u'track': {u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}], u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'], u'composer': u'', u'year': 2012, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Myth', u'title': u'Vesij\xe4rvi', u'albumArtist': u'Geographer', u'trackNumber': 9, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'Tkrxk4atoacsxytnakhoyf52sem', u'nid': u'Tkrxk4atoacsxytnakhoyf52sem', u'estimatedSize': u'10513796', u'albumId': u'Bfvh2badashiwhiwapiolvhd34m', u'genre': u'Alternative/Indie', u'kind': u'sj#track', u'artist': u'Geographer', u'durationMillis': u'262000'}, u'navigational_result': False, u'score': 65.39643096923828, u'type': u'1', u'best_result': False}, {u'navigational_result': False, u'station': {u'kind': u'sj#radioStation', u'seed': {u'kind': u'sj#radioSeed', u'artistId': u'A4aopp74j4zwlxd4pbvtfnncf3i', u'seedType': u'3'}, u'imageUrls': [{u'url': u'http://lh3.googleusercontent.com/ZIgRRfW34Kv2vJ5O1-5GqsmSVSkJBMn9g60hnvc-0UaHLAUWBXbg__pfHE2MG7Wp60fKW-F0bsw'}], u'name': u'Geographer'}, u'type': u'6', u'best_result': False}, {u'navigational_result': False, u'station': {u'kind': u'sj#radioStation', u'seed': {u'trackId': u'Txwp6zm4g6qrc3zkhihpz67ryza', u'kind': u'sj#radioSeed', u'seedType': u'2'}, u'imageUrls': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}], u'name': u'Kaleidoscope'}, u'type': u'6', u'best_result': False}, {u'navigational_result': False, u'station': {u'kind': u'sj#radioStation', u'seed': {u'trackId': u'Tkrxk4atoacsxytnakhoyf52sem', u'kind': u'sj#radioSeed', u'seedType': u'2'}, u'imageUrls': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}], u'name': u'Vesij\xe4rvi'}, u'type': u'6', u'best_result': False}]}
[ERROR] (shared:282): the response format for Search was not recognized.

Failed to validate field 'entries' list schema: additional property 'station' not defined by 'properties' are not allowed in list item

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{'url': 'https://mclients.googleapis.com/sj/v1.11/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': u'Geographer Kaleidoscope', 'max-results': 50}, 'method': 'GET'}

'{\n "kind": "sj#searchresponse",\n "entries": [\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "Geographer",\n    "artistArtRef": "http://lh3.googleusercontent.com/ZIgRRfW34Kv2vJ5O1-5GqsmSVSkJBMn9g60hnvc-0UaHLAUWBXbg__pfHE2MG7Wp60fKW-F0bsw",\n    "artistId": "A4aopp74j4zwlxd4pbvtfnncf3i",\n    "artist_bio_attribution": {\n     "kind": "sj#attribution",\n     "source_title": "artist representative"\n    }\n   },\n   "score": 165.54998779296875,\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "1",\n   "track": {\n    "kind": "sj#track",\n    "title": "Kaleidoscope",\n    "artist": "Geographer",\n    "composer": "",\n    "album": "Myth",\n    "albumArtist": "Geographer",\n    "year": 2012,\n    "trackNumber": 3,\n    "genre": "Alternative/Indie",\n    "durationMillis": "277000",\n    "albumArtRef": [\n     {\n      "url": "http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA"\n     }\n    ],\n    "discNumber": 1,\n    "e...'

A traceback follows:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 249, in perform
    cls.validate(response, parsed_response)
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/mobileclient.py", line 262, in validate
    return validictory.validate(msg, cls._res_schema)
  File "/usr/lib/python2.7/site-packages/validictory/__init__.py", line 33, in validate
    return v.validate(data, schema)
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 569, in validate
    self._validate(data, schema)
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 572, in _validate
    self.__validate("_data", {"_data": data}, schema)
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 603, in __validate
    newschema.get(schemaprop))
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 230, in validate_properties
    properties.get(eachProp))
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 603, in __validate
    newschema.get(schemaprop))
  File "/usr/lib/python2.7/site-packages/validictory/validator.py", line 276, in validate_items
    e.value)
ValidationException: Failed to validate field 'entries' list schema: additional property 'station' not defined by 'properties' are not allowed in list item
[DEBUG] (GMusicProxy:376): {'album_hits': [],
 'artist_hits': [{u'artist': {u'artistArtRef': u'http://lh3.googleusercontent.com/ZIgRRfW34Kv2vJ5O1-5GqsmSVSkJBMn9g60hnvc-0UaHLAUWBXbg__pfHE2MG7Wp60fKW-F0bsw',
                              u'artistId': u'A4aopp74j4zwlxd4pbvtfnncf3i',
                              u'artist_bio_attribution': {u'kind': u'sj#attribution',
                                                          u'source_title': u'artist representative'},
                              u'kind': u'sj#artist',
                              u'name': u'Geographer'},
                  u'best_result': False,
                  u'navigational_result': False,
                  u'score': 165.54998779296875,
                  u'type': u'2'}],
 'playlist_hits': [],
 'song_hits': [{u'best_result': False,
                u'navigational_result': False,
                u'score': 150.19752502441406,
                u'track': {u'album': u'Myth',
                           u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}],
                           u'albumArtist': u'Geographer',
                           u'albumAvailableForPurchase': True,
                           u'albumId': u'Bfvh2badashiwhiwapiolvhd34m',
                           u'artist': u'Geographer',
                           u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'],
                           u'composer': u'',
                           u'contentType': u'2',
                           u'discNumber': 1,
                           u'durationMillis': u'277000',
                           u'estimatedSize': u'11104163',
                           u'genre': u'Alternative/Indie',
                           u'kind': u'sj#track',
                           u'nid': u'Txwp6zm4g6qrc3zkhihpz67ryza',
                           u'storeId': u'Txwp6zm4g6qrc3zkhihpz67ryza',
                           u'title': u'Kaleidoscope',
                           u'trackAvailableForPurchase': True,
                           u'trackAvailableForSubscription': True,
                           u'trackNumber': 3,
                           u'trackType': u'7',
                           u'year': 2012},
                u'type': u'1'},
               {u'best_result': False,
                u'navigational_result': False,
                u'score': 65.39643096923828,
                u'track': {u'album': u'Myth',
                           u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}],
                           u'albumArtist': u'Geographer',
                           u'albumAvailableForPurchase': True,
                           u'albumId': u'Bfvh2badashiwhiwapiolvhd34m',
                           u'artist': u'Geographer',
                           u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'],
                           u'composer': u'',
                           u'contentType': u'2',
                           u'discNumber': 1,
                           u'durationMillis': u'262000',
                           u'estimatedSize': u'10513796',
                           u'genre': u'Alternative/Indie',
                           u'kind': u'sj#track',
                           u'nid': u'Tkrxk4atoacsxytnakhoyf52sem',
                           u'storeId': u'Tkrxk4atoacsxytnakhoyf52sem',
                           u'title': u'Vesij\xe4rvi',
                           u'trackAvailableForPurchase': True,
                           u'trackAvailableForSubscription': True,
                           u'trackNumber': 9,
                           u'trackType': u'7',
                           u'year': 2012},
                u'type': u'1'}]}
[DEBUG] (GMusicProxy:378): I'm feeling lucky: lets select the first song!
[INFO] (GMusicProxy:388): Selected song: Geographer - Kaleidoscope (Txwp6zm4g6qrc3zkhihpz67ryza)
[DEBUG] (GMusicProxy:389): {u'best_result': False,
 u'navigational_result': False,
 u'score': 150.19752502441406,
 u'track': {u'album': u'Myth',
            u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}],
            u'albumArtist': u'Geographer',
            u'albumAvailableForPurchase': True,
            u'albumId': u'Bfvh2badashiwhiwapiolvhd34m',
            u'artist': u'Geographer',
            u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'],
            u'composer': u'',
            u'contentType': u'2',
            u'discNumber': 1,
            u'durationMillis': u'277000',
            u'estimatedSize': u'11104163',
            u'genre': u'Alternative/Indie',
            u'kind': u'sj#track',
            u'nid': u'Txwp6zm4g6qrc3zkhihpz67ryza',
            u'storeId': u'Txwp6zm4g6qrc3zkhihpz67ryza',
            u'title': u'Kaleidoscope',
            u'trackAvailableForPurchase': True,
            u'trackAvailableForSubscription': True,
            u'trackNumber': 3,
            u'trackType': u'7',
            u'year': 2012},
 u'type': u'1'}
[DEBUG] (shared:202): GetStoreTrack(args=[u'Txwp6zm4g6qrc3zkhihpz67ryza'], kwargs={})
[DEBUG] (shared:243): {u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}], u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'], u'composer': u'', u'year': 2012, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Myth', u'title': u'Kaleidoscope', u'albumArtist': u'Geographer', u'trackNumber': 3, u'discNumber': 1, u'albumAvailableForPurchase': False, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'Txwp6zm4g6qrc3zkhihpz67ryza', u'nid': u'Txwp6zm4g6qrc3zkhihpz67ryza', u'estimatedSize': u'11104163', u'albumId': u'Bfvh2badashiwhiwapiolvhd34m', u'genre': u'Alternative/Indie', u'kind': u'sj#track', u'artist': u'Geographer', u'durationMillis': u'277000'}
[INFO] (GMusicProxy:175): Streaming song with id 'Txwp6zm4g6qrc3zkhihpz67ryza': Geographer - Kaleidoscope
[DEBUG] (GMusicProxy:176): {u'album': u'Myth',
 u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}],
 u'albumArtist': u'Geographer',
 u'albumAvailableForPurchase': False,
 u'albumId': u'Bfvh2badashiwhiwapiolvhd34m',
 u'artist': u'Geographer',
 u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'],
 u'composer': u'',
 u'contentType': u'2',
 u'discNumber': 1,
 u'durationMillis': u'277000',
 u'estimatedSize': u'11104163',
 u'genre': u'Alternative/Indie',
 u'kind': u'sj#track',
 u'nid': u'Txwp6zm4g6qrc3zkhihpz67ryza',
 u'storeId': u'Txwp6zm4g6qrc3zkhihpz67ryza',
 u'title': u'Kaleidoscope',
 u'trackAvailableForPurchase': True,
 u'trackAvailableForSubscription': True,
 u'trackNumber': 3,
 u'trackType': u'7',
 u'year': 2012}
[DEBUG] (shared:202): GetStreamUrl(args=[u'Txwp6zm4g6qrc3zkhihpz67ryza', '3709629877331607957', 'hi'], kwargs={})
[DEBUG] (shared:243): https://r4---sn-p5qlsns6.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=d618669b6c46a633&itag=25&source=skyjam&begin=0&upn=rwbBSc5pIy8&o=01423689343908048365&ratebypass=yes&ip=71.63.37.143&ipbits=0&expire=1444523777&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,o,pl,ratebypass,source,upn&signature=700892A01BA96D1B36774B943385D6505F38DCAD.7CDAAEB986E079FD3295AB02C0648C31600863A5&key=cms1&mm=31&mn=sn-p5qlsns6&ms=au&mt=1444523632&mv=m&nh=IgpwcjAxLmlhZDI2KgkxMjcuMC4wLjE&pl=17
[DEBUG] (GMusicProxy:198): streaming url: https://r4---sn-p5qlsns6.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=d618669b6c46a633&itag=25&source=skyjam&begin=0&upn=rwbBSc5pIy8&o=01423689343908048365&ratebypass=yes&ip=71.63.37.143&ipbits=0&expire=1444523777&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,o,pl,ratebypass,source,upn&signature=700892A01BA96D1B36774B943385D6505F38DCAD.7CDAAEB986E079FD3295AB02C0648C31600863A5&key=cms1&mm=31&mn=sn-p5qlsns6&ms=au&mt=1444523632&mv=m&nh=IgpwcjAxLmlhZDI2KgkxMjcuMC4wLjE&pl=17
[WARNING] (GMusicProxy:452): Detected connection reset.

**Comment by diraimondo** [comment]
I can confirm the bug using the same URL: `/get_by_search?type=song&artist=Geographer&title=Kaleidoscope`. It should caused by some changes in the data reported by Google to gmusicapi. I can just forward this report to @simon-weber.

**Comment by simon-weber** [comment]
I believe this was fixed in https://github.com/simon-weber/gmusicapi/issues/351; can you try upgrading?

**Comment by onespaceman** [comment]
Thanks for the quick reply
I updated gmusicapi with makepkg (the AUR package is outdated), but still get the same result.

[INFO] (mobileclient:69): authenticated
[DEBUG] (GMusicProxy:558): Fetching lastest version of gmusicproxy...
[DEBUG] (GMusicProxy:560): latest available version: 1.0.1
[DEBUG] (GMusicProxy:561): installed version: 1.0.1
[INFO] (GMusicProxy:641): Listening on port 9999...
[DEBUG] (GMusicProxy:34): request path: /get_by_search?type=song&artist=Geographer&title=Kaleidoscope
[INFO] (GMusicProxy:353): Searching for song with query: Geographer Kaleidoscope
[DEBUG] (shared:201): Search(args=[u'Geographer Kaleidoscope', 50], kwargs={})
[DEBUG] (shared:242): {u'kind': u'sj#searchresponse', u'clusterOrder': [u'5', u'2', u'3', u'1', u'7', u'6', u'4', u'8'], u'entries': [{u'navigational_result': False, u'score': 166.8472442626953, u'type': u'2', u'best_result': False, u'artist': {u'kind': u'sj#artist', u'artistArtRef': u'http://lh3.googleusercontent.com/ZIgRRfW34Kv2vJ5O1-5GqsmSVSkJBMn9g60hnvc-0UaHLAUWBXbg__pfHE2MG7Wp60fKW-F0bsw', u'name': u'Geographer', u'artistId': u'A4aopp74j4zwlxd4pbvtfnncf3i', u'artist_bio_attribution': {u'kind': u'sj#attribution', u'source_title': u'artist representative'}}}, {u'track': {u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}], u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'], u'composer': u'', u'year': 2012, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Myth', u'title': u'Kaleidoscope', u'albumArtist': u'Geographer', u'trackNumber': 3, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'Txwp6zm4g6qrc3zkhihpz67ryza', u'nid': u'Txwp6zm4g6qrc3zkhihpz67ryza', u'estimatedSize': u'11104163', u'albumId': u'Bfvh2badashiwhiwapiolvhd34m', u'genre': u'Alternative/Indie', u'kind': u'sj#track', u'artist': u'Geographer', u'durationMillis': u'277000'}, u'navigational_result': False, u'score': 150.02247619628906, u'type': u'1', u'best_result': False}, {u'track': {u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}], u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'], u'composer': u'', u'year': 2012, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Myth', u'title': u'Vesij\xe4rvi', u'albumArtist': u'Geographer', u'trackNumber': 9, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'Tkrxk4atoacsxytnakhoyf52sem', u'nid': u'Tkrxk4atoacsxytnakhoyf52sem', u'estimatedSize': u'10513796', u'albumId': u'Bfvh2badashiwhiwapiolvhd34m', u'genre': u'Alternative/Indie', u'kind': u'sj#track', u'artist': u'Geographer', u'durationMillis': u'262000'}, u'navigational_result': False, u'score': 65.28504180908203, u'type': u'1', u'best_result': False}, {u'navigational_result': False, u'station': {u'kind': u'sj#radioStation', u'seed': {u'kind': u'sj#radioSeed', u'artistId': u'A4aopp74j4zwlxd4pbvtfnncf3i', u'seedType': u'3'}, u'imageUrls': [{u'url': u'http://lh3.googleusercontent.com/ZIgRRfW34Kv2vJ5O1-5GqsmSVSkJBMn9g60hnvc-0UaHLAUWBXbg__pfHE2MG7Wp60fKW-F0bsw'}], u'name': u'Geographer'}, u'type': u'6', u'best_result': False}, {u'navigational_result': False, u'station': {u'kind': u'sj#radioStation', u'seed': {u'trackId': u'Txwp6zm4g6qrc3zkhihpz67ryza', u'kind': u'sj#radioSeed', u'seedType': u'2'}, u'imageUrls': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}], u'name': u'Kaleidoscope'}, u'type': u'6', u'best_result': False}, {u'navigational_result': False, u'station': {u'kind': u'sj#radioStation', u'seed': {u'trackId': u'Tkrxk4atoacsxytnakhoyf52sem', u'kind': u'sj#radioSeed', u'seedType': u'2'}, u'imageUrls': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}], u'name': u'Vesij\xe4rvi'}, u'type': u'6', u'best_result': False}]}
[DEBUG] (GMusicProxy:376): {'album_hits': [],
 'artist_hits': [{u'artist': {u'artistArtRef': u'http://lh3.googleusercontent.com/ZIgRRfW34Kv2vJ5O1-5GqsmSVSkJBMn9g60hnvc-0UaHLAUWBXbg__pfHE2MG7Wp60fKW-F0bsw',
                              u'artistId': u'A4aopp74j4zwlxd4pbvtfnncf3i',
                              u'artist_bio_attribution': {u'kind': u'sj#attribution',
                                                          u'source_title': u'artist representative'},
                              u'kind': u'sj#artist',
                              u'name': u'Geographer'},
                  u'best_result': False,
                  u'navigational_result': False,
                  u'score': 166.8472442626953,
                  u'type': u'2'}],
 'playlist_hits': [],
 'song_hits': [{u'best_result': False,
                u'navigational_result': False,
                u'score': 150.02247619628906,
                u'track': {u'album': u'Myth',
                           u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}],
                           u'albumArtist': u'Geographer',
                           u'albumAvailableForPurchase': True,
                           u'albumId': u'Bfvh2badashiwhiwapiolvhd34m',
                           u'artist': u'Geographer',
                           u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'],
                           u'composer': u'',
                           u'contentType': u'2',
                           u'discNumber': 1,
                           u'durationMillis': u'277000',
                           u'estimatedSize': u'11104163',
                           u'genre': u'Alternative/Indie',
                           u'kind': u'sj#track',
                           u'nid': u'Txwp6zm4g6qrc3zkhihpz67ryza',
                           u'storeId': u'Txwp6zm4g6qrc3zkhihpz67ryza',
                           u'title': u'Kaleidoscope',
                           u'trackAvailableForPurchase': True,
                           u'trackAvailableForSubscription': True,
                           u'trackNumber': 3,
                           u'trackType': u'7',
                           u'year': 2012},
                u'type': u'1'},
               {u'best_result': False,
                u'navigational_result': False,
                u'score': 65.28504180908203,
                u'track': {u'album': u'Myth',
                           u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}],
                           u'albumArtist': u'Geographer',
                           u'albumAvailableForPurchase': True,
                           u'albumId': u'Bfvh2badashiwhiwapiolvhd34m',
                           u'artist': u'Geographer',
                           u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'],
                           u'composer': u'',
                           u'contentType': u'2',
                           u'discNumber': 1,
                           u'durationMillis': u'262000',
                           u'estimatedSize': u'10513796',
                           u'genre': u'Alternative/Indie',
                           u'kind': u'sj#track',
                           u'nid': u'Tkrxk4atoacsxytnakhoyf52sem',
                           u'storeId': u'Tkrxk4atoacsxytnakhoyf52sem',
                           u'title': u'Vesij\xe4rvi',
                           u'trackAvailableForPurchase': True,
                           u'trackAvailableForSubscription': True,
                           u'trackNumber': 9,
                           u'trackType': u'7',
                           u'year': 2012},
                u'type': u'1'}]}
[DEBUG] (GMusicProxy:378): I'm feeling lucky: lets select the first song!
[INFO] (GMusicProxy:388): Selected song: Geographer - Kaleidoscope (Txwp6zm4g6qrc3zkhihpz67ryza)
[DEBUG] (GMusicProxy:389): {u'best_result': False,
 u'navigational_result': False,
 u'score': 150.02247619628906,
 u'track': {u'album': u'Myth',
            u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}],
            u'albumArtist': u'Geographer',
            u'albumAvailableForPurchase': True,
            u'albumId': u'Bfvh2badashiwhiwapiolvhd34m',
            u'artist': u'Geographer',
            u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'],
            u'composer': u'',
            u'contentType': u'2',
            u'discNumber': 1,
            u'durationMillis': u'277000',
            u'estimatedSize': u'11104163',
            u'genre': u'Alternative/Indie',
            u'kind': u'sj#track',
            u'nid': u'Txwp6zm4g6qrc3zkhihpz67ryza',
            u'storeId': u'Txwp6zm4g6qrc3zkhihpz67ryza',
            u'title': u'Kaleidoscope',
            u'trackAvailableForPurchase': True,
            u'trackAvailableForSubscription': True,
            u'trackNumber': 3,
            u'trackType': u'7',
            u'year': 2012},
 u'type': u'1'}
[DEBUG] (shared:201): GetStoreTrack(args=[u'Txwp6zm4g6qrc3zkhihpz67ryza'], kwargs={})
[DEBUG] (shared:242): {u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}], u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'], u'composer': u'', u'year': 2012, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Myth', u'title': u'Kaleidoscope', u'albumArtist': u'Geographer', u'trackNumber': 3, u'discNumber': 1, u'albumAvailableForPurchase': False, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'Txwp6zm4g6qrc3zkhihpz67ryza', u'nid': u'Txwp6zm4g6qrc3zkhihpz67ryza', u'estimatedSize': u'11104163', u'albumId': u'Bfvh2badashiwhiwapiolvhd34m', u'genre': u'Alternative/Indie', u'kind': u'sj#track', u'artist': u'Geographer', u'durationMillis': u'277000'}
[INFO] (GMusicProxy:175): Streaming song with id 'Txwp6zm4g6qrc3zkhihpz67ryza': Geographer - Kaleidoscope
[DEBUG] (GMusicProxy:176): {u'album': u'Myth',
 u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/q2aPx5xQCi3pb-sB8lz_s_oUK_8DowIU_fNBE2VS7dgLoA0b5p_StUX4EoIBCvoTQwkRYuD3OA'}],
 u'albumArtist': u'Geographer',
 u'albumAvailableForPurchase': False,
 u'albumId': u'Bfvh2badashiwhiwapiolvhd34m',
 u'artist': u'Geographer',
 u'artistId': [u'A4aopp74j4zwlxd4pbvtfnncf3i'],
 u'composer': u'',
 u'contentType': u'2',
 u'discNumber': 1,
 u'durationMillis': u'277000',
 u'estimatedSize': u'11104163',
 u'genre': u'Alternative/Indie',
 u'kind': u'sj#track',
 u'nid': u'Txwp6zm4g6qrc3zkhihpz67ryza',
 u'storeId': u'Txwp6zm4g6qrc3zkhihpz67ryza',
 u'title': u'Kaleidoscope',
 u'trackAvailableForPurchase': True,
 u'trackAvailableForSubscription': True,
 u'trackNumber': 3,
 u'trackType': u'7',
 u'year': 2012}
[DEBUG] (shared:201): GetStreamUrl(args=[u'Txwp6zm4g6qrc3zkhihpz67ryza', '3709629877331607957', 'hi'], kwargs={})
[DEBUG] (shared:242): https://r4---sn-p5qlsns6.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=d618669b6c46a633&itag=25&source=skyjam&begin=0&upn=oVIA6WqJB7o&o=01423689343908048365&ratebypass=yes&ip=71.63.37.143&ipbits=0&expire=1444608938&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,o,pl,ratebypass,source,upn&signature=71C98873923A7FA3224C52B7760E5BBC35B72B.249C17D2EE19353DD9911F4A287DDB52E26C02FB&key=cms1&mm=31&mn=sn-p5qlsns6&ms=au&mt=1444608773&mv=m&nh=IgpwcjAyLmlhZDI2KgkxMjcuMC4wLjE&pl=17
[DEBUG] (GMusicProxy:198): streaming url: https://r4---sn-p5qlsns6.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=d618669b6c46a633&itag=25&source=skyjam&begin=0&upn=oVIA6WqJB7o&o=01423689343908048365&ratebypass=yes&ip=71.63.37.143&ipbits=0&expire=1444608938&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,o,pl,ratebypass,source,upn&signature=71C98873923A7FA3224C52B7760E5BBC35B72B.249C17D2EE19353DD9911F4A287DDB52E26C02FB&key=cms1&mm=31&mn=sn-p5qlsns6&ms=au&mt=1444608773&mv=m&nh=IgpwcjAyLmlhZDI2KgkxMjcuMC4wLjE&pl=17
[WARNING] (GMusicProxy:452): Detected connection reset.

**Comment by diraimondo** [comment]
I'm just upgraded to `gmusicapi` 7.0.0 and I can confirm that the validation error has been fixed. Thank you @simon-weber : sorry, I didn't note such change in 7.0.0 changelog. Such version will be a requirement for `gmusicproxy` now.

@onespaceman : you should note that the second debug log is different: there is no validation exception now. We are not getting any result in the URL request because there are not song that match such request. I've also tested this request on the web interface: https://play.google.com/music/listen#/sr/Geographer+Kaleidoscope As you can note there are no single song available. We don't support videos. 

Going to close this.
